name: Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [-f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create Zip
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archieve Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-artifact
          path: ${{ github.sha }}.zip
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release from ${{ github.run_number }}
          body: New Release for ${{ github.sha }}. Release notes for documentation
          draft: false
          prerelease: false
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: zipped-artifact
      - name: upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./${{ github.sha }}.zip
          asset_name: source_code_with_libraries.zip
          asset_content_type: application/zip
          
            
          
      
