name: PublishtoS3Bucket
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [-f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create Zip
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archieve Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-artifact
          path: ${{ github.sha }}.zip
  publishtos3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: zipped-artifact
      - name: Configure AWS cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to s3
        run: aws s3 cp ${{ github.sha }}.zip s3://githubactions2022wertfg/${{ github.sha }}.zip
